//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 饥荒秘籍输入器.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("饥荒秘籍输入器.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 兔子,rabbit
        ///火鸡,perd
        ///乌鸦,crow
        ///红雀,robin
        ///雪雀,robin_winter
        ///蝴蝶,butterfly
        ///萤火虫,fireflies
        ///蜜蜂,bee
        ///杀人蜂,killerbee
        ///苍蝇,flies
        ///蚊子,mosquito
        ///青蛙,frog
        ///牛,beefalo
        ///小牛,babybeefalo
        ///闪电羊,lightninggoat
        ///猪人,pigman
        ///猪守卫,pigguard
        ///兔人,bunnyman
        ///鱼人,merm
        ///洞穴蜘蛛,spider_hider
        ///喷射蜘蛛,spider_spitter
        ///地面小蜘蛛,spider
        ///地面绿蜘蛛,spider_warrior
        ///蜘蛛女王,spiderqueen
        ///白蜘蛛,spider_dropper
        ///猎狗,hound
        ///红色猎狗,firehound
        ///冰狗,icehound
        ///触手,tentacle
        ///巨型触手,tentacle_garden
        ///树精,leif
        ///稀有树精,leif_sparse
        ///海象,walrus
        ///小海象,little_walrus
        ///小高鸟,smallbird
        ///青年高鸟,teenbird
        ///高鸟,t [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 动物 {
            get {
                return ResourceManager.GetString("动物", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 斧子,axe
        ///黄金斧头,goldenaxe
        ///露西斧子,lucy
        ///锤子,hammer
        ///镐,pickaxe
        ///黄金镐,goldenpickaxe
        ///铲子,shovel
        ///黄金铲子,goldenshovel
        ///草叉,pitchfork
        ///剃刀,razor
        ///捕虫网,bugnet
        ///鱼竿,fishingrod
        ///多功能工具,multitool_axe_pickaxe
        ///行走手杖,cane
        ///陷阱,trap
        ///鸟陷阱,birdtrap
        ///牙齿陷阱,trap_teeth
        ///麦斯威尔的牙齿陷阱,trap_teeth_maxwell
        ///背包,backpack
        ///猪皮包,piggyback
        ///坎普斯背包,krampus_sack
        ///雨伞,umbrella
        ///草伞,grass_umbrella
        ///保温石,heatrock
        ///草席卷,bedroll_straw
        ///毛皮铺盖,bedroll_furry
        ///火炬,torch
        ///提灯,lantern
        ///南瓜灯,pumpkin_lantern
        ///指南针,compass
        ///化肥,fertilizer
        ///灭火器,firesuppressor
        ///缝纫工具包,sewing_kit
        ///矛,s [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 工具武器 {
            get {
                return ResourceManager.GetString("工具武器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 营火,campfire
        ///石头营火,firepit
        ///冷火,coldfire
        ///石头冷火,coldfirepit
        ///锅,cookpot
        ///冰箱,icebox
        ///寒冰温度计,winterometer
        ///雨量计,rainometer
        ///一般农田,slow_farmplot
        ///高级农田,fast_farmplot
        ///午睡小屋,siestahut
        ///帐篷,tent
        ///路牌,homesign
        ///鸟笼,birdcage
        ///晾肉架,meatrack
        ///避雷针,lightning_rod
        ///盆栽,pottedfern
        ///暗夜照明灯,nightlight
        ///影灯,nightmarelight
        ///科学机器,researchlab
        ///炼金术引擎,researchlab2
        ///阴影操纵者,researchlab3
        ///灵子分解器,researchlab4
        ///木箱,treasurechest
        ///骷髅箱,skullchest
        ///华丽的箱子,pandoraschest
        ///大华丽的箱子,minotaurchest
        ///蜻蜓箱子,dragonflychest
        ///草墙,wall_hay_item
        ///木墙,wall_wood_item
        ///石墙,wall [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 建筑 {
            get {
                return ResourceManager.GetString("建筑", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 草,cutgrass
        ///树枝,twigs
        ///木头,log
        ///木炭,charcoal
        ///灰,ash
        ///采下的芦苇,cutreeds
        ///荧光果,lightbulb
        ///花瓣,petals
        ///噩梦花瓣,petals_evil
        ///松果,pinecone
        ///叶子,foliage
        ///摘下的苔藓,cutlichen
        ///虫子果,wormlight
        ///食人花种子,lureplantbulb
        ///燧石,flint
        ///硝石,nitre
        ///红宝石,redgem
        ///蓝宝石,bluegem
        ///紫宝石,purplegem
        ///绿宝石,greengem
        ///橙宝石,orangegem
        ///黄宝石,yellowgem
        ///岩石,rocks
        ///黄金,goldnugget
        ///铥矿石,thulecite
        ///铥矿碎片,thulecite_pieces
        ///绳子,rope
        ///木板,boards
        ///石砖,cutstone
        ///纸,papyrus
        ///犬牙,houndstooth
        ///猪皮,pigskin
        ///兔人尾巴,manrabbit_tail
        ///蜘蛛丝,silk
        ///蜘蛛腺体,spidergland
        ///蜘蛛卵,spidereggsack
        ///胡子,beardhair
        ///牛毛, [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 材料类 {
            get {
                return ResourceManager.GetString("材料类", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 花,flower
        ///噩梦花,flower_evil
        ///长在地上的胡萝卜,carrot_planted
        ///长在地上的草,grass
        ///草根,depleted_grass
        ///长草簇,dug_grass
        ///树苗,sapling
        ///可种的树苗,dug_sapling
        ///果树丛,berrybush
        ///可种的果树丛,dug_berrybush
        ///果树丛2,berrybush2
        ///可种的果树丛2,dug_berrybush2
        ///尖刺灌木,marsh_bush
        ///可种的尖刺灌木,dug_marsh_bush
        ///芦苇,reeds
        ///洞穴苔藓,lichen
        ///蕨类植物,cave_fern
        ///树,evergreen
        ///无松果的树,evergreen_sparse
        ///针叶树,marsh_tree
        ///洞穴香蕉树,cave_banana_tree
        ///活树,livingtree
        ///橡树,deciduoustree
        ///高橡树,deciduoustree_tall
        ///矮橡树,deciduoustree_short
        ///红蘑菇,red_mushroom
        ///绿蘑菇,green_mushroom
        ///蓝蘑菇,blue_mushroom
        ///高蘑菇树,mu [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 植物 {
            get {
                return ResourceManager.GetString("植物", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 草帽,strawhat
        ///花环,flowerhat
        ///牛毛帽,beefalohat
        ///羽毛帽,featherhat
        ///猪皮帽,footballhat
        ///高礼帽,tophat
        ///兔耳罩,earmuffshat
        ///冬帽,winterhat
        ///矿工帽,minerhat
        ///蜘蛛帽,spiderhat
        ///蜂帽,beehat
        ///海象帽,walrushat
        ///蜗牛帽子,slurtlehat
        ///丛林帽,bushhat
        ///远古王冠,ruinshat
        ///防雨帽,rainhat
        ///冰帽,icehat
        ///西瓜帽,watermelonhat
        ///浣熊帽,catcoonhat
        ///瓦丝格雷斯帽,wathgrithrhat
        ///木盔甲,armorwood
        ///草盔甲,armorgrass
        ///大理石盔甲,armormarble
        ///夜魔盔甲,armor_sanity
        ///蜗牛龟盔甲,armorsnurtleshell
        ///远古盔甲,armorruins
        ///小巧背心,sweatervest
        ///夏日背心,trunkvest_summer
        ///寒冬背心,trunkvest_winter
        ///饥饿腰带,armorslurper
        ///雨衣,raincoat
        ///韦伯头骨, [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 穿戴 {
            get {
                return ResourceManager.GetString("穿戴", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 胡萝卜,carrot
        ///熟胡萝卜,carrot_cooked
        ///浆果,berries
        ///熟浆果,berries_cooked
        ///南瓜,pumpkin
        ///熟南瓜,pumpkin_cooked
        ///火龙果,dragonfruit
        ///熟火龙果,dragonfruit_cooked
        ///石榴,pomegranate
        ///熟石榴,pomegranate_cooked
        ///玉米,corn
        ///熟玉米,corn_cooked
        ///榴莲,durian
        ///熟榴莲,durian_cooked
        ///茄子,eggplant
        ///熟茄子,eggplant_cooked
        ///洞穴香蕉,cave_banana
        ///熟洞穴香蕉,cave_banana_cooked
        ///橡果,acorn
        ///熟橡果,acorn_cooked
        ///仙人掌肉,cactus_meat
        ///西瓜,watermelon
        ///采摘的红蘑菇,red_cap
        ///煮熟的红蘑菇,red_cap_cooked
        ///采摘的绿蘑菇,green_cap
        ///煮熟的绿蘑菇,green_cap_cooked
        ///煮熟的蓝蘑菇,blue_cap_cooked
        ///采摘的蓝蘑菇,blue_cap
        ///种子,seeds
        ///熟种子,se [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 食物 {
            get {
                return ResourceManager.GetString("食物", resourceCulture);
            }
        }
    }
}
