/**************************************************************************
 ADOBE SYSTEMS INCORPORATED
 Copyright (C) 1994-2006 Adobe Systems Incorporated
 All rights reserved.

 NOTICE: Adobe permits you to use, modify, and distribute this file
 in accordance with the terms of the Adobe license agreement
 accompanying it. If you have received this file from a source other
 than Adobe, then your use, modification, or distribution of it
 requires the prior written permission of Adobe.

 ---------------------------------------------------------------------
 EnumAVConvExtSnip.cpp

This snippet enumerates all files file formats that Acrobat can support in the SaveAs or OpenAs PDF file menus.

Implementation:
-	enumerate file extensions that can be converted to PDF with AVConversionEnumToPDFConverters
-	enumerate file extensions that can be converted from PDF with AVConversionEnumFromPDFConverters

Usage:
-	select AcroSDK Snippets > Snippet Runner UI > AV Layer > Document > Enumerate File Conversion Extension
-	two lists of file extensions should be displayed in the debug window, one is generated by the ConvertToPDF 
handlers and the other is generated by the ConvertFromPDF handlers.
 
NOTE: 
Some file extensions are displayed multiple times and some are displayed as empty strings. This is because  
the snippet enumerates all the AVConversion Handlers that are registered by the viewer. If one extension has been 
registered in more than one handler, it will be displayed multiple times and if the extension has been registered as 
an empty or localized string, it will be displayed as an empty string in the Debug Window.   
**********************************************************************************************************************************/

#include "SnippetRunner.h"
#include "SnippetRunnerUtils.h"

static ASInt32 gNumToPDFExt;
static ASInt32 gNumFromPDFExt;

/*
	User defined callback: AVConversionFromPDFEnumProc
*/
static ACCB1 ASBool ACCB2 myAVConversionFromPDFEnumProc(AVConversionFromPDFHandler handler,AVConversionEnumProcData data)
{
	AVFileFilterRec filter = handler->convFilter;
	ASUns16 numFileExt = filter.numFileDescs;
	
	char buff[300];
	sprintf(buff,"Filter %d found with unique ID of \"%s\".\n",gNumFromPDFExt++,handler->uniqueID);
	Console::displayString(buff);
	sprintf(buff,"Description: %s.\n",ASTextGetScriptText(filter.filterDescription,kASRomanScript));
	Console::displayString(buff);

	sprintf(buff,"Filter supports %d file types\n",numFileExt);
	Console::displayString(buff);
	sprintf(buff,"File Extensions: ");
	for (ASInt32 i = 0; i < numFileExt; i++)
	{
		// cases exist where this entry is NULL (for locale considerations)
		if (strlen(handler->convFilter.fileDescs[i].extension)>0)
		{
			sprintf(buff,"%s %s",buff,filter.fileDescs[i].extension);			
		}
	}
	Console::displayString(buff);
	Console::displayString("\n");
	return true;
}

/*
	User defined AVConversionToPDFEnumProc
*/
static ACCB1 ASBool ACCB2 myAVConversionToPDFEnumProc(AVConversionToPDFHandler handler,AVConversionEnumProcData data)
{
	AVFileFilterRec filter = handler->convFilter;
	ASUns16 numFileExt = filter.numFileDescs;
	
	char buff[300];
	sprintf(buff,"Filter %d found with unique ID of \"%s\".]n",gNumToPDFExt++,handler->uniqueID);
	Console::displayString(buff);
	sprintf(buff,"Description: %s.\n",ASTextGetScriptText(filter.filterDescription,kASRomanScript));
	Console::displayString(buff);

	sprintf(buff,"Filter supports %d file types\n",numFileExt);
	Console::displayString(buff);
	sprintf(buff,"File Extensions: ");
	for (ASInt32 i = 0; i < numFileExt; i++)
	{
		if (strlen(handler->convFilter.fileDescs[i].extension)>0)
		{
			sprintf(buff,"%s %s",buff,filter.fileDescs[i].extension);
		}
	}
	Console::displayString(buff);
	Console::displayString("\n");
	return true;
}

/** This snippet enumerates all file formats that Acrobat can support in the SaveAs or OpenAs PDF file menus.

Implementation:
<ul>
<li>	enumerate file extensions that can be converted to PDF with AVConversionEnumToPDFConverters
<li>	enumerate file extensions that can be converted from PDF with AVConversionEnumFromPDFConverters
</ul>
	@testfile none
	@see AVConversionEnumToPDFConverters
	@see AVConversionEnumFromPDFConverters
*/  
static ACCB1 void ACCB2 EnumAVConvExtSnip()
{
	gNumFromPDFExt = 0;
	gNumToPDFExt = 0;
	Console::displayString("Conversion to PDF");
	Console::displayString("------------------------------------------");
	AVConversionEnumToPDFConverters(myAVConversionToPDFEnumProc, NULL);

	Console::displayString("Conversion from PDF");
	cout << "------------------------------------------" << endl;
	AVConversionEnumFromPDFConverters(myAVConversionFromPDFEnumProc, NULL);
}

// Register the snippet
SNIPRUN_REGISTER(EnumAVConvExtSnip, "AV Layer:Document:Enumerate File Conversion Extensions", "This snippet enumerates all file formats that Acrobat supports for import/export")
